

dataset={
			'Philip Espina': {'Lady in the Water': 2.5, 
							'Snakes on a Plane': 3.5,
							'Just My Luck': 3.0, 
							'Superman Returns': 3.5, 
							'You, Me and Dupree': 2.5,
							'The Night Listener': 3.0},
			'Gene Seymour': {'Lady in the Water': 3.0, 
							'Snakes on a Plane': 3.5,
							'Just My Luck': 1.5,
							 'Superman Returns': 5.0, 
							 'The Night Listener': 3.0,
							'You, Me and Dupree': 3.5},

			'Michael Phillips': {'Lady in the Water': 2.5, 
								'Snakes on a Plane': 3.0,
								'Superman Returns': 3.5,
								 'The Night Listener': 4.0},
			'Claudia Puig': {'Snakes on a Plane': 3.5, 
							'Just My Luck': 3.0,
							'The Night Listener': 4.5, 
							'Superman Returns': 4.0,
							'You, Me and Dupree': 2.5},
			'Mick LaSalle': {'Lady in the Water': 3.0, 
							'Snakes on a Plane': 4.0,
							'Just My Luck': 2.0, 
							'Superman Returns': 3.0, 
							'The Night Listener': 3.0,
							'You, Me and Dupree': 2.0},
			'Jack Matthews': {'Lady in the Water': 3.0, 
							'Snakes on a Plane': 4.0,
							'The Night Listener': 3.0, 
							'Superman Returns': 5.0, 
							'You, Me and Dupree': 3.5},
			'Geronyl': {'Snakes on a Plane':4.5,
					'You, Me and Dupree':1.0,
					'Superman Returns':4.0},

			'Espina': {'Lady in the Water': 1.5, 
							'Snakes on a Plane': 3.5,
							'Just My Luck': 4.0, 
							'Superman Returns': 3.5, 
							'You, Me and Dupree': 2.5,
							'The Night Listener': 3.0},
			'Gene': {'Lady in the Water': 5.0, 
							'Snakes on a Plane': 2.5,
							'Just My Luck': 3.5,
							 'Superman Returns': 2.0, 
							 'The Night Listener': 1.0,
							'You, Me and Dupree': 4.5},

			'Michael': {'Lady in the Water': 3.0, 
								'Snakes on a Plane': 2.0,
								'Superman Returns': 4.5,
								 'The Night Listener': 1.0},
			'Claudia': {'Snakes on a Plane': 1.5, 
							'Just My Luck': 4.0,
							'The Night Listener': 3.5, 
							'Superman Returns': 2.0,
							'You, Me and Dupree': 2.5},
			'Mick': {'Lady in the Water': 1.0, 
							'Snakes on a Plane': 2.0,
							'Just My Luck': 5.0, 
							'Superman Returns': 3.0, 
							'The Night Listener': 3.0,
							'You, Me and Dupree': 3.5},
			'Jack': {'Lady in the Water': 3.0, 
							'Snakes on a Plane': 4.5,
							'The Night Listener': 3.0, 
							'Superman Returns': 2.5, 
							'You, Me and Dupree': 3.5},
			'Pina': {'Lady in the Water': 2.5, 
							'Snakes on a Plane': 1.5,
							'Just My Luck': 1.0, 
							'Superman Returns': 3.5, 
							'You, Me and Dupree': 2.5,
							'The Night Listener': 3.0},
			'Seur': {'Lady in the Water': 1.0, 
							'Snakes on a Plane': 3.5,
							'Just My Luck': 1.5,
							 'Superman Returns': 3.0, 
							 'The Night Listener': 2.0,
							'You, Me and Dupree': 5.0},
			'Phils': {'Lady in the Water': 2.5, 
								'Snakes on a Plane': 3.0,
								'Superman Returns': 3.5,
								 'The Night Listener': 2.0},
			'Pug': {'Snakes on a Plane': 2.5, 
							'Just My Luck': 4.0,
							'The Night Listener': 4.5, 
							'Superman Returns': 1.0,
							'You, Me and Dupree': 2.5},
			'Lale': {'Lady in the Water': 3.0, 
							'Snakes on a Plane': 4.0,
							'Just My Luck': 1.0, 
							'Superman Returns': 3.0, 
							'The Night Listener': 3.0,
							'You, Me and Dupree': 2.0},
			'Mats': {'Lady in the Water': 4.0, 
							'Snakes on a Plane': 1.0,
							'The Night Listener': 5.0, 
							'Superman Returns': 2.0, 
							'You, Me and Dupree': 4.5},
			'Phina': {'Lady in the Water': 1.0, 
							'Snakes on a Plane': 2.5,
							'Just My Luck': 3.5, 
							'Superman Returns': 1.5, 
							'You, Me and Dupree': 3.5,
							'The Night Listener': 2.0},
			'Geur': {'Lady in the Water': 1.0, 
							'Snakes on a Plane': 2.5,
							'Just My Luck': 4.5,
							 'Superman Returns': 3.0, 
							 'The Night Listener': 2.0,
							'You, Me and Dupree': 3.5},

			'Micllips': {'Lady in the Water': 1.5, 
								'Snakes on a Plane': 2.0,
								'Superman Returns': 3.5,
								 'The Night Listener': 4.0},
			'Cig': {'Snakes on a Plane': 4.5, 
							'Just My Luck': 4.0,
							'The Night Listener': 4.5, 
							'Superman Returns': 1.0,
							'You, Me and Dupree': 2.5},
			'Salle': {'Lady in the Water': 3.0, 
							'Snakes on a Plane': 4.0,
							'Just My Luck': 2.0, 
							'Superman Returns': 2.0, 
							'The Night Listener': 5.0,
							'You, Me and Dupree': 2.0},
			'Jacse': {'Lady in the Water': 1.0, 
							'Snakes on a Plane': 3.0,
							'The Night Listener': 3.0, 
							'Superman Returns': 2.0, 
							'You, Me and Dupree': 3.5},
			'Gero': {'Snakes on a Plane':4.5,
					 'The Night Listener': 4.0,
					 'You, Me and Dupree':2.0,
					'Superman Returns':1.0},
			'Espa': {'Lady in the Water': 2.5, 
							'Snakes on a Plane': 4.5,
							'Just My Luck': 4.0, 
							'Superman Returns': 1.5, 
							'You, Me and Dupree': 4.5,
							'The Night Listener': 3.0},
			'Genie': {'Lady in the Water': 1.0, 
							'Snakes on a Plane': 2.5,
							'Just My Luck': 3.5,
							 'Superman Returns': 1.0, 
							 'The Night Listener': 1.0,
							'You, Me and Dupree': 4.5},

			'Michaelo': {'Lady in the Water': 2.0, 
								'Snakes on a Plane': 3.0,
								'Superman Returns': 2.5,
								 'The Night Listener': 3.0},
			'Cloey': {'Snakes on a Plane': 4.5, 
							'Just My Luck': 5.0,
							'The Night Listener': 3.5, 
							'Superman Returns': 1.0,
							'You, Me and Dupree': 2.5},
			'Mickey': {'Lady in the Water': 1.0, 
							'Snakes on a Plane': 3.0,
							'Just My Luck': 5.0, 
							'Superman Returns': 4.0, 
							'The Night Listener': 3.0,
							'You, Me and Dupree': 3.5},
			'Jackey': {'Lady in the Water': 3.0, 
							'Snakes on a Plane': 3.5,
							'The Night Listener': 1.0, 
							'Superman Returns': 2.5, 
							'You, Me and Dupree': 2.5},
			'Phipina': {'Lady in the Water': 2.5, 
							'Snakes on a Plane': 1.0,
							'Just My Luck': 2.0, 
							'Superman Returns': 4.5, 
							'You, Me and Dupree': 2.5,
							'The Night Listener': 3.0},
			'Seyr': {'Lady in the Water': 1.0, 
							'Snakes on a Plane': 3.5,
							'Just My Luck': 1.5,
							 'Superman Returns': 3.0, 
							 'The Night Listener': 2.0,
							'You, Me and Dupree': 5.0},
			'Plips': {'Lady in the Water': 2.5, 
								'Snakes on a Plane': 3.0,
								'Superman Returns': 3.5,
								 'The Night Listener': 2.0},
			'Luggie': {'Snakes on a Plane': 2.5, 
							'Just My Luck': 4.0,
							'The Night Listener': 4.5, 
							'Superman Returns': 1.0,
							'You, Me and Dupree': 2.5},
			'Lalley': {'Lady in the Water': 3.0, 
							'Snakes on a Plane': 4.0,
							'Just My Luck': 1.0, 
							'Superman Returns': 3.0, 
							'The Night Listener': 3.0,
							'You, Me and Dupree': 2.0},
			'Maethews': {'Lady in the Water': 4.0, 
							'Snakes on a Plane': 1.0,
							'The Night Listener': 5.0, 
							'Superman Returns': 2.0, 
							'You, Me and Dupree': 4.5}}


							